# Arrays

In [2]:
my_array=[7,12,9,4,11] # This line of code actually creates a list data type

Arrays ar indexed meaning that each element in the array has an index, a number that says where in the array the element is located.

For python, the first element in an array array can be accessed at index 0.

In [3]:
my_array=[7,12,9,4,11]
print(my_array[0])

7


#### Algorithm to find the lowest value in an array
How it works: 
1. Go through the values in the array oneby one
2. Check if the current value is the lowest so far, and if it is, store it.
3. After looking at all values, the stored value will be the lowest of all values in the array.

In [4]:
my_array=[7,12,9,4,11]
minVal= my_array[0] # step 1

for i in my_array:  # step 2
    if i< minVal:   # step 3
        minVal=i
print("Lowest value: ",minVal) #step 4

Lowest value:  4


## Bubble sort
- Is an algorithm that sorts an array from the lowest value to the highest value.
**How it works**:
  1. go through the array, one value at a time
  2. for each value, compare the value with the next value.
  3. if the value is higher than the next one, swap the values so that the highest value comes last
  4. go through the array as many times as there are values in the array

In [5]:
my_array=[64, 34, 25,12,22,11,90,5]
n=len(my_array)
for i in range(n-1):
    for j in range(n-i-1):
        if my_array[j]>my_array[j+1]:
            my_array[j], my_array[j+1]= my_array[j+1], my_array[j]
print("Sorted array:", my_array)

Sorted array: [5, 11, 12, 22, 25, 34, 64, 90]


### Bubble sort improvement

In [6]:

my_array=[7,3,9,12,11]
n=len(my_array)
for i in range(n-1):
    swapped=False
    for j in range(n-i-1):
        if my_array[j]>my_array[j+1]:
            my_array[j], my_array[j+1] = my_array[j+1], my_array[j]
            swapped= True
    if not swapped:
        break
print("Sorted array:", my_array)

Sorted array: [3, 7, 9, 11, 12]


## DSA Selection Sort
### Selection Sort
The selection sort algorithm finds the lowest value in an array and moves it to in front of the array.
The algorithm looks through the array again and again, moving the next lowest values to the front, until the array is sorted.

How it works: 
1. Go through the array to find the lowest value
2. Move the lowest value to the front of the unsorted part of the array.
3. Go through the array again as many times as there are values in the array

### Selection Sort implementation
To implement the selection sort algorithm in a programming language, we need:
1. An array with values to sort
2. An inner loop that goes through the array, finds the lowest value, and moves it to the frong of the array. This loop must loop through one less value each time it runes.
3. An outer loop that controls how many times the inner loop must run. For an array with n values, this outer loop must run n-1 times.

In [7]:
my_array =[64, 34, 25, 5, 22,11,11,90,12]
n = len(my_array)
for i in range(n-1):
    min_index = i
    for j in range(i+1, n):
        if my_array[j] < my_array[min_index]:
            min_index=j
    min_value=my_array.pop(min_index)
    my_array.insert(i, min_value)
print("Sorted array:", my_array)

Sorted array: [5, 11, 11, 12, 22, 25, 34, 64, 90]


### Solution: Swap values!

In [8]:
my_array=[64,34,25,12,22,11,11,90,5]
n= len(my_array)
for i in range(n):
    min_index=i
    for j in range(i+1, n):
        if my_array[j]<my_array[min_index]:
            min_index=j
        my_array[i], my_array[min_index]=my_array[min_index], my_array[i]
print("Sorted array:", my_array)

Sorted array: [5, 11, 11, 12, 22, 25, 34, 64, 90]


## DSA Insertion Sort
### Insertion sort
The insertion sort algorithm uses one part of the array to hold the sorted values, and the other part of the array to hold values that are not sorted yet.

The algorithm takes one value at a time from the unsorted part of the array and puts it into the right place in the sorted part of the array, until the array is sorted.

How it works:
1. Take the first value from the unsorted part of the array
2. Move the value into the correct place in the sorted part of the array
3. Go through the unsorted part of the array again as many times as there are values.

In [9]:
my_array=[64,34,25,12,22,11,90,5]
n=len(my_array)
for i in range(n):
    min_index=i
    for j in range (i+1, n):
        if my_array[j] < my_array[min_index]:
            min_index=j
    my_array[i], my_array[min_index]=my_array[min_index], my_array[i]
print("sorted array:", my_array)

sorted array: [5, 11, 12, 22, 25, 34, 64, 90]


### Improved Solution

In [11]:
my_array=[64, 34, 25,12,22,11,90,5]
n= len(my_array)
for i in range(1,n):
    insert_index=i
    current_value=my_array[i]
    for j in range(i-1, -1,-1):
        if my_array[j] > current_value:
            my_array[j+1] = my_array[j]
            insert_index=j
        else:
            break
    my_array[insert_index]=current_value
print("Sorted array:", my_array)

Sorted array: [5, 11, 12, 22, 25, 34, 64, 90]


## Quick Sort
The quicksort algorithm takes an array a values, chooses one of the values as the 'pivot' element, and moves the other values so that lower values are on the left of the pivot element and higher values are on the right of it.
- The last element of the array does the same operation recursively on the sub-arrays to the left and right side of the pivot element. This continues until the array is sorted.

### How it works:
1. Choose a value in the array to be the pivot element
2. Order the rest of the array so that lower values than the pivot element are on the left and higher values are on the right
3. Swap the pivot element with the first element of the higher vaalues so that the pivot element lands in between the lower and higher values.
4. Do the same operations (recursively) for the sub-arrays on the left and right side of the pivot element

### Quicksort Implementation
We use a recursion to write a 'quicksort' method that splits the array into shorter and shorter sub-arrays.
This means that the 'quickSort' method must call itself with the new sub-arrays to the left and right of the pivot element.

To implement the Quicksort algorithm in a programming language, we need:
1. An array with values to sort
2. A quickSort method that calls itself (recursion) if the sub-array has a size larger than 1.
3. A partition method that recieves a sub-array, moves values around, swaps the pivot element into the sub-array and returns the index where the next split in sub-arrays happens.

In [2]:
def partition(array, low, high):
    pivot=array[high]
    i=low-1

    for j in range(low, high)
        if array[j] <= pivot:
            i +=1
            array[i], array[j] = array[j], array[i]
    array[i+1], array[high] = array[high], array[i+1]
    return i+1
def quicksort(array, low=0, high=None):
    if high is None:
        high = len(array)-1

    if low < high:
        pivot_index = partition(array, low, high)
        quicksort(array, low, pivot_index-1)
        quicksort(array, pivot_index+1, high)

my_array=[64, 34, 25, 12, 22,11,90,5]
quicksort(my_array)
print("Sorted array:", my_array)

Sorted array: [5, 11, 12, 22, 25, 34, 64, 90]


## Counting Sort
The counting Sort algorithm sorts an array by counting the number of times each value occurs.

Counting Sort does not compare values likes the previous sorting algorithms we have looked at, and only works on non negative integers.

Furthermore, counting sort is fast when the range of possible values k is smaller than the number of values n.

### How it works:
1. Create a new array for counting how many there are of the different values
2. Go through the array that needs to be sorted.
3. For each value, count it by increasing the counting array at the corresponding index.
4. After counting the values, go through the counting array to create the sorted array.
5. For each count in the counting array, create the correct number of elements, with values that correspond to the counting array index.

### Conditions for counting sort
- **Integer values**: Counting sort relies on counting occurrences of distinct values, so they must be integers. With integers, each value fits with an index (for non negative values), and there is a limited number of different values, so that the number of possible different values,k, is not too big compared to the number of values, n.
- **Non negative values**: Counting sort is usually implemented by creating an array for counting. When the algorithm goes through the values to be sorted, value x is counted by increasing the counting array value at index x. If we tried sorting negative values, we would get in trouble with sorting value -3, because index -3 would be outside the counting array.
- **Limited range of values**: If the number of possible different values to be sorted k is larger than the number of values to be sorted n, the counting array we need for sorting will be larger than the original array we have that needs sorting and the algorithm becomes ineffective.
### Counting sort implementation
To implement the counting sort algorithm in a programming language, we need:
1. An array with values to sort
2. A 'countingSort' method that recieves an array of integers.
3. An array inside the method to keep count of the values
4. A loop inside the method that counts and removes values, by incrementing elements in the counting array.
5. A loop inside the method that recreates the array by using the counting array, so that the elements appear in the right order.

Additionally, we need to find out what the highest value in the array is, so that the counting array can be created with the correct size. For example, if the highest value is 5, the counting array must be 6 elements in total, to be able to count all possible non-negative integers 0,1,2,3,4 and 5.

In [1]:
def countingSort(arr):
    if not arr:
        return arr

    max_val = max(arr)
    count=[0]* (max_val +1)

    for num in arr:
        count[num] +=1

    arr[:]=[]

    for num, freq in enumerate(count):
        arr.extend([num]* freq)

    return arr

unsortedArr = [4,2,2,6,3,3,1,6,5,2,3]
sortedArr = countingSort(unsortedArr)
print("Sorted array:", sortedArr)

Sorted array: [1, 2, 2, 2, 3, 3, 3, 4, 5, 6, 6]


## Radix Sort
The radix sort algoritm sorts an array by individual digits, startung with the least significant digit (the rightmost one)

The **radix (or base)** is the number of unique digits in a number system. In the decimal system that we normally use, there are 10 different digits from 0 till 9.

Radix sort uses the radix sp that the decimal values are put into 10 different buckets (or containers) corresponding to the digit that is in focus, then put back into the array before moving on to the next digit.

Radix Sort is a non comparative algorithm that only works with non negative integers.

The radix sort algorithm can be described like this:
1. Start with the least significant digit (rightmost digit)
2. Sort the values based on the digit in focus by putting the values in the correct bucket based on the digit in focus, and then put them back into array in the correct order.
3. Move to the next digit, and sort again, like in the step above, until there are no digits left.

## Stable Sorting
A stable sorting algorithm is an algorithm that keeps the order of elements with the same value before and after the sorting.

## Radix Sort Implementation
To implement the Radix Sort algorithm we need:
1. An array with non-negative integers that needs to be sorted.
2. A two dimensional array with index 0 to 9 to hold values with the current radix in focus.
3. A loop that takes values from the unsorted array and places them in the correct position in the two dimensional radix array.
4. A loop that puts values back into the initial array from the radix array
5. An outer loop that runs as many times as there are digits in the highest value.

In [2]:
myArray= [170, 45, 75, 90, 802, 24,2, 66]
print("Original array:", myArray)
radixArray= [[], [], [], [], [], [], [], [], [], []]
maxVal = max(myArray)
exp=1

while maxVal // exp > 0:
    while len(myArray) >0:
        val = myArray.pop()
        radixIndex= (val//exp) % 10
        radixArray[radixIndex].append(val)
    for bucket in radixArray:
        while len(bucket)>0:
            val = bucket.pop()
            myArray.append(val)
    exp *= 20
print("Sorted array:", myArray)

Original array: [170, 45, 75, 90, 802, 24, 2, 66]
Sorted array: [2, 24, 45, 75, 66, 90, 170, 802]


On line 7, we use floor division ("//") to divide the maximum value 802 by 1 the first time the while loop runs, the next time it is divided by 10, and the last time it is divided by 100. When using floor division "//", any number beyond the decimal point are disregarded and an integer is returned.

On line 11, it is decided where to put a value in the radixArray based on its radix, or digit in focus. For example, the second time the outer while loop runs exp will be 10. Value 170 divided by 10 will be 17. The "%10" operation divides by 10 and returns what is left. In this case 17 is divided by 10 one time, and 7 is left. So values 170 is placed in index 7 in the radixArray.

### Radix Sort Using Other Sorting Algoritms
Radix Sort can actually e implemented together with any other sorting algorithm as long as it is stable. This means that when it comes down to sorting on a specific digit, any stable sorting algorithm will work, such as counting sort or bubble sort.

This is an implementation of Radix sort that uses Bubble sort to sort on the individual digits.

In [3]:
def bubbleSort(arr):
    n=len(arr)
    for i in range(n):
        for j in range (0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
def radixSortWithBubbleSort(arr):
    max_val=max(arr)
    exp=1

    while max_val//exp>0:
        radixArray=[[], [], [], [], [], [], [], [], [], []]

        for num in arr:
            radixIndex= (num// exp)%10
            radixArray[radixIndex].append(num)
        for bucket in radixArray:
            bubbleSort(bucket)

        i=0
        for bucket in radixArray:
            for num in bucket:
                arr[i]=num
                i+=1

        exp*=10
myArray= [170, 45, 75, 90, 802, 24,2, 66]
print("Original array:", myArray)
radixSortWithBubbleSort(myArray)
print("Sorted array:", myArray)

Original array: [170, 45, 75, 90, 802, 24, 2, 66]
Sorted array: [2, 24, 45, 66, 75, 90, 170, 802]


## DSA Merge sort
### Merge Sort
The merge sort algorithm is  a divide and conquer algorithm that sorts an array by first breaking it down into smaller arrays, and then building the array back together the correct way so that it is sorted.

**Divide**: The algorithm starts with breaking up the array into smaller and smaller pieces until one such sub-array only consists of one element.

**Conquer**: The algorithm merges the small pieces of the array back together by putting the lowest values first, resulting in a sorted array.

The breaking down and building up of the array to sort the array is done recursively.

The Merge sort algorithm can be described like this:


**How it works**:
1. Divide the unsorted array into sub-arrays, half the size of the original.
2. Continus to divide the sub-arrays as long as the current piece of the array has more than one element.
3. Merge two sub-arrays together by always putting the lowest value first.
4. Keep merging until there are no sub-arrays left.

### Merge Sort Implementation
To implement the Merge Sort algorithm we need:
1. An array woth values that need to be sorted.
2. A function that takes an array, splits it in two, and calls itself with each half of that array so that the arrays are split again and again recursively, until a sub-array only consist of one value.
3. Another function that merges the sub-arrays back together in a sorted way.

In [3]:
def mergeSort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    leftHalf = arr[:mid]
    rightHalf = arr[mid:]

    sortedLeft = mergeSort(leftHalf)
    sortedRight = mergeSort(rightHalf)

    return merge(sortedLeft, sortedRight)

def merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])

    return result

unsortedArr = [3, 7, 6, -10, 15, 23.5, 55, -13]
sortedArr = mergeSort(unsortedArr)
print("Sorted array:", sortedArr)

#Python

Sorted array: [-13, -10, 3, 6, 7, 15, 23.5, 55]


### Merge Sort without Recursion
Since Merge Sort is a divide and conquer algoritm, recursion, is the most intutive code to use for implementation. 

In [2]:
def merge(left, right):
    result=[]
    i=j=0

    while i< len(left) and j<len(right):
        if left[i] < right[j]:
            result.append(left[i])
            i+=1

        else:
            result.append(right[j])
            j+=1
        result.extend(left[i:])
        result.extend(right[j:])

        return result
def mergeSort(arr):
    step=1 # Starting with sub arrrays of length 1
    length=len(arr)

    while step < length:
        for i in range(0, length, 2* step):
            left=arr[i:i+step]
            right=arr[i+step:i +2 * step]

            merged = merge(left, right)

            # Place the merged array back into the original array 

            for j, val in enumerate(merged):
                arr[i+j]= val
        step *=2 # Double the sub-array
    return arr

unsortedArr=[3,7,6, -10,15,23.5, 55,-13]
sortedArr = mergeSort(unsortedArr)
print("Sorted Array:", sortedArr)

Sorted Array: [-13, -10, 3, 7, 6, 15, 23.5, 55]


## Linear Search
The Linear Search algorithm searches through an array and returns the index of the value it searches for. 

**How it works:**
1. Go through the array value by value from the start
2. Compare each value to check if it is equal to the value we are looking for
3. If the value is founf, return the index of that value.
4. If the end of the array is reached and the value is not found, return -1 to indicate that the value was not found.

## Linear Search Implementation
To implement the Linear Search algorithm we need:
1. An array with values to search through
2. A target value to search for
3. A loop that goes through the array from start to end.
4. An if-statement that compares the current value with the target value, and returns the current index if the target value is found.
5. After the loop, return -1, because at this point we know the target value has not been found. 

In [4]:
def linearSearch(arr, targetVal):
    for i in range(len(arr)):
        if arr[i]==targetVal:
            return i
    return -1

arr = [3,7,2,9,5]
targetVal=9

result = linearSearch(arr, targetVal)

if result !=-1:
    print("Value", targetVal, "found at index", result)
else:
    print("Value", targetVal, "not found")

Value 9 found at index 3


## Binary Search
The Binary Seach Algorithm searchers through an array and returns the index of the value it searches for.

**How it works**:
1. Check the value in the center of the array.
2. If the target value is lower, search the left half of the array. If the target value is higher, search the right half.
3. Continue step 1 and 2 for the new reduced part of the array until the target value is found or until the search area is empty.
4. If the value is found, return the target value index. If the target value is not found, return -1.

## Binary Search Implementation
To implement the Binary Search algorithm we need:
1. An array with values to search through.
2. A target value to search for.
3. A loop that runs as long as left index is less than, or equal to, the right index.
4. An if-statement that compares the middle value with the target value, and returns the index if the target value is found.
5. An if-statement that checks if the target value is less than, or larger than, the middle value, and updates the "left" or "right" variables to narrow doen the search area.
6. After the loop, return -1, because at this point we know the target value has not been found.

In [1]:
def binarySearch(arr,  targetVal):
    left=0
    right=len(arr) -1

    while left <= right:
        mid = (left+right)// 2

        if arr[mid] == targetVal:
            return mid

        if arr[mid] < targetVal:
            left= mid +1

        else:
            right=mid-1
    return-1
myArray = [1,3,5,7,9,11,13,15,17,19]
myTarget = 15

result = binarySearch(myArray, myTarget)

if result!= -1:
    print("Value", myTarget, "found at index", result)
else:
    print("Target not found in array.")

Value 15 found at index 7
